### ISSUE TITLE
ModuleNotFoundError: No module named 'nuscenes.prediction'

### ISSUE THREAD

**Issue by YuRui-Learning** [nutonomy/nuscenes-devkit#1023]
Traceback (most recent call last):
  File "../tools/test.py", line 16, in <module>
    from projects.mmdet3d_plugin.datasets.builder import build_dataloader
  File "/root/UniAD/projects/mmdet3d_plugin/__init__.py", line 5, in <module>
    from .datasets.pipelines import (
  File "/root/UniAD/projects/mmdet3d_plugin/datasets/__init__.py", line 1, in <module>
    from .nuscenes_e2e_dataset import NuScenesE2EDataset
  File "/root/UniAD/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py", line 20, in <module>
    from .eval_utils.nuscenes_eval_motion import MotionEval
  File "/root/UniAD/projects/mmdet3d_plugin/datasets/eval_utils/nuscenes_eval_motion.py", line 59, in <module>
    from .eval_utils import load_prediction, load_gt, accumulate, accumulate_motion, \
  File "/root/UniAD/projects/mmdet3d_plugin/datasets/eval_utils/eval_utils.py", line 12, in <module>
    from nuscenes.prediction import PredictHelper, convert_local_coords_to_global
ModuleNotFoundError: No module named 'nuscenes.prediction'

**Comment by whyekit-motional** [comment]
This looks like some installation issue - if you are installing via MMDet3D, then it's best to check with the maintainers of that repo
