### ISSUE TITLE
Nuscenes2Kitti

### ISSUE THREAD

**Issue by adajdioadhwoadh** [nutonomy/nuscenes-devkit#1125]
Why I convert the Nuscenes dataset to Kitti, there are 20 parameters in the result. As I know, the Kitti I used is **{'frame', 'track_id', 'type', 'truncated', 'occluded', 'alpha', 'bbox_left', 'bbox_top', 'bbox_right', 'bbox_bottom', 'height', 'width', 'length', 'x', 'y', 'z', 'rotation_y'}**, but I'm not sure the result is **'frame', 'track_id', 'type', 'truncated', 'occluded', 'alpha', 'bbox_left', 'bbox_top', 'bbox_right', 'bbox_bottom', 'height', 'width', 'length', 'x', 'y', 'z', 'rotation_y', 'score', 'num_lidar_points', 'keyframe'**.

And another issue is some frames are repeated, what can I do to deal with it?

The code I use is in V2B/nuscenes-devkit-master/python-sdk/nuscenes/scripts/export_kitti.py.

**Comment by whyekit-motional** [comment]
@adajdioadhwoadh pls verify if you are doing the conversion via:
```
python export_kitti.py kitti_res_to_nuscenes --nusc_kitti_dir ~/nusc_kitti
```

**Comment by AimanPattah** [comment]
i got different problem
Traceback (most recent call last):
  File "/home/maxxsui/nuscenes-devkit/python-sdk/nuscenes/scripts/export_kitti.py", line 362, in <module>
    fire.Fire(KittiConverter)
  File "/home/maxxsui/.local/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/maxxsui/.local/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/maxxsui/.local/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/maxxsui/nuscenes-devkit/python-sdk/nuscenes/scripts/export_kitti.py", line 84, in __init__
    self.nusc = NuScenes(version=nusc_version)
  File "/home/maxxsui/nuscenes-devkit/python-sdk/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: /data/sets/nuscenes/v1.0-mini

**Comment by whyekit-motional** [comment]
@maxxsuiii pls check that `/data/sets/nuscenes/v1.0-mini` exists on your machine
