### ISSUE TITLE
Converting trainval 01 part to KITTI format Error

### ISSUE THREAD

**Issue by judyqiu1996** [nutonomy/nuscenes-devkit#255]
I am downloading one subset of the trainval dataset and try to convert it to kitti dataset but I got the error below.

```
python3 export_kitti.py nuscenes_gt_to_kitti --nusc_kitti_dir ~/nucesc_kitti_trainval/ --split train
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 84.7 seconds.
======
Reverse indexing ...
Done reverse indexing in 25.8 seconds.
======
Traceback (most recent call last):
  File "export_kitti.py", line 368, in <module>
    fire.Fire(KittiConverter)
  File "/home/yujiaq3/venv_python3/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/yujiaq3/venv_python3/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/yujiaq3/venv_python3/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "export_kitti.py", line 157, in nuscenes_gt_to_kitti
    assert (velo_to_cam_rot.round(0) == np.array([[0, -1, 0], [0, 0, -1], [1, 0, 0]])).all()
AssertionError
```

**Comment by holger-nutonomy** [comment]
Hi. I have just run this script on the entire train set using
```
python3 export_kitti.py nuscenes_gt_to_kitti --split train --nusc_version v1.0-trainval --image_count 100000000
```
and it works. I've attached the calibration and label folders here:
[calib.zip](https://github.com/nutonomy/nuscenes-devkit/files/3861795/calib.zip)
[label_2.zip](https://github.com/nutonomy/nuscenes-devkit/files/3861796/label_2.zip)
Unfortunately the image and lidar folders are too big to share them here (48GB).

I am not sure what went wrong on your side. Can you print out the value of `velo_to_cam_rot` ?

**Comment by judyqiu1996** [comment]
It's still the same error as before.
```
 python3 export_kitti.py nuscenes_gt_to_kitti --split train --nusc_version v1.0-trainval --image_count 100000000
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 95.8 seconds.
======
Reverse indexing ...
Done reverse indexing in 23.7 seconds.
======
Traceback (most recent call last):
  File "export_kitti.py", line 368, in <module>
    fire.Fire(KittiConverter)
  File "/home/yujiaq3/venv_python3/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/yujiaq3/venv_python3/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/yujiaq3/venv_python3/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "export_kitti.py", line 157, in nuscenes_gt_to_kitti
    assert (velo_to_cam_rot.round(0) == np.array([[0, -1, 0], [0, 0, -1], [1, 0, 0]])).all()
AssertionError
```
And this is the value of  `velo_to_cam_rot`
```
[[-0.83366746 -0.55165401 -0.02600816]
 [ 0.0242518   0.01047966 -0.99965095]
 [ 0.55173401 -0.83400721  0.00464205]]
```

**Comment by holger-nutonomy** [comment]
As I said it works on my side. Can you update your nuscenes-devkit and tell me what OS and Python and pyquaternion version you are using?

**Comment by judyqiu1996** [comment]
@holger-nutonomy 
I use the latest nuscenes-devkit. And I am using 01 part of the data, ubuntu 16.04, python 3.7.4, pyquaternion 0.9.5.

**Comment by holger-nutonomy** [comment]
I have the exact same setup, except I am using all of the training data. Try downloading the other parts to see if it works then. Or work only with the mini split.

**Comment by judyqiu1996** [comment]
@holger-nutonomy I actually tried with mini dataset, and it works. Probably it only works with the whole training dataset.
