### ISSUE TITLE
NameError: name 'Dict' is not defined

### ISSUE THREAD

**Issue by swirlingsand** [nutonomy/nuscenes-devkit#34]
```
Traceback (most recent call last):
3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
  File "play.py", line 1, in <module>
    from nuscenes.nuscenes import NuScenes
  File "A:\Sync\work\nuscenes-devkit\python-sdk\nuscenes\nuscenes.py", line 30, in <module>
    from nuscenes.utils.data_classes import LidarPointCloud, RadarPointCloud, Box
  File "A:\Sync\work\nuscenes-devkit\python-sdk\nuscenes\utils\data_classes.py", line 20, in <module>
    class PointCloud(ABC):
  File "A:\Sync\work\nuscenes-devkit\python-sdk\nuscenes\utils\data_classes.py", line 60, in PointCloud
    min_distance: float=1.0) -> Tuple[self, np.ndarray]:
NameError: name 'Dict' is not defined
```

Typo? should be `dict`?

**Comment by holger-nutonomy** [comment]
Fixed this issue and merged to master. Note that Dict is part of the typing module.
