### ISSUE TITLE
Error on running prediction baseline 

### ISSUE THREAD

**Issue by amiryanj** [nutonomy/nuscenes-devkit#369]
Traceback (most recent call last):
  File "/home/cyrus/workspace2/nuScenes/python-sdk/nuscenes/eval/prediction/baseline_model_inference.py", line 11, in <module>
    from nuscenes.eval.prediction.config import load_prediction_config
  File "/home/cyrus/workspace2/nuScenes/python-sdk/nuscenes/eval/prediction/config.py", line 7, in <module>
    from nuscenes.eval.prediction.metrics import Metric, deserialize_metric
  File "/home/cyrus/workspace2/nuScenes/python-sdk/nuscenes/eval/prediction/metrics.py", line 337
    maps: Dict[str, NuScenesMap] = load_all_maps(helper)
        ^
SyntaxError: invalid syntax

**Comment by holger-nutonomy** [comment]
This looks like you are using an old version of Python (maybe 2.7) ? Please try to setup the environment as described at https://github.com/nutonomy/nuscenes-devkit/blob/master/setup/installation.md
