### ISSUE TITLE
Attempting to verify environment returns: KeyError: 'NUIMAGES'

### ISSUE THREAD

**Issue by martindisley** [nutonomy/nuscenes-devkit#461]
Hello, 

I tried running the tests to verify the environment and received the error below.
I'm running on Ubuntu 20.04 LTS (please let me know if there is any other system information you need)
I followed the [installation instructions](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/installation.md#setup-matplotlib-backend) and everything ran smoothly until there.

I can also run the [nuscenes tutorial notebook](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_tutorial.ipynb) without error. I'm pretty sure I've got the data in the right place.

Any help much appreciated... 

```
(nuscenes) martin@bigmachine:~/nuscenes-devkit/python-sdk$ python -m unittest
Traceback (most recent call last):
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/main.py", line 130, in parseArgs
    self._do_discovery([])
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/loader.py", line 414, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/loader.py", line 414, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/loader.py", line 460, in _find_test_path
    return self.loadTestsFromModule(module, pattern=pattern), False
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/loader.py", line 93, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/unittest/suite.py", line 57, in addTests
    for test in tests:
  File "/home/martin/nuscenes-devkit/python-sdk/nuimages/tests/test_attributes.py", line 24, in __init__
    self.dataroot = os.environ['NUIMAGES']
  File "/home/martin/anaconda3/envs/nuscenes/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'NUIMAGES'
```

**Comment by holger-nutonomy** [comment]
It looks like you are missing this line:
`export NUIMAGES="/data/sets/nuimages"`
https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/installation.md#setup-environment-variable
