### ISSUE TITLE
KeyError: 'singapore-onenorth' is resulted upon verifying the nuscenes-devkit installation

### ISSUE THREAD

**Issue by RevathiTS** [nutonomy/nuscenes-devkit#477]
Hi,
I have downloaded the nuscenes_lidarseg dataset by following the instructions in link
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_lidarseg_tutorial.ipynb

The nuscene python dev-kit is installed by following the instructions as in link
https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/installation.md#install-python

Upon verifying the nuscenes-devkit installation in virtal environment  by using the command  "python -m unittest", the error has come as attached in the sceenshot.How this error can be solved?

![InstallatationVergicationError](https://user-images.githubusercontent.com/72782377/95819792-69450400-0d44-11eb-8575-773259496dbd.PNG)

======================================================================
ERROR: test_boston (nuscenes.eval.prediction.tests.test_metrics.TestOffRoadRate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/tests/test_metrics.py", line 299, in test_boston
    self._do_test('boston-seaport', predictions, 2/3)
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/tests/test_metrics.py", line 287, in _do_test
    np.testing.assert_allclose(off_road_rate(np.array([]), prediction), np.array([answer]))
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/metrics.py", line 382, in __call__
    drivable_area = self.drivable_area_polygons[map_name]
KeyError: 'boston-seaport'

======================================================================
ERROR: test_hollandvillage (nuscenes.eval.prediction.tests.test_metrics.TestOffRoadRate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/tests/test_metrics.py", line 331, in test_hollandvillage
    self._do_test('singapore-hollandvillage', predictions, 0)
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/tests/test_metrics.py", line 287, in _do_test
    np.testing.assert_allclose(off_road_rate(np.array([]), prediction), np.array([answer]))
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/metrics.py", line 382, in __call__
    drivable_area = self.drivable_area_polygons[map_name]
KeyError: 'singapore-hollandvillage'

======================================================================
ERROR: test_one_north (nuscenes.eval.prediction.tests.test_metrics.TestOffRoadRate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/tests/test_metrics.py", line 312, in test_one_north
    self._do_test('singapore-onenorth', predictions, 1/3)
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/tests/test_metrics.py", line 287, in _do_test
    np.testing.assert_allclose(off_road_rate(np.array([]), prediction), np.array([answer]))
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/metrics.py", line 382, in __call__
    drivable_area = self.drivable_area_polygons[map_name]
KeyError: 'singapore-onenorth'

======================================================================
ERROR: test_queenstown (nuscenes.eval.prediction.tests.test_metrics.TestOffRoadRate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/tests/test_metrics.py", line 320, in test_queenstown
    self._do_test('singapore-queenstown', predictions, 1/2)
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/tests/test_metrics.py", line 287, in _do_test
    np.testing.assert_allclose(off_road_rate(np.array([]), prediction), np.array([answer]))
  File "/home/teroot/nuscenes-devkit/python-sdk/nuscenes/eval/prediction/metrics.py", line 382, in __call__
    drivable_area = self.drivable_area_polygons[map_name]
KeyError: 'singapore-queenstown'

----------------------------------------------------------------------
Ran 200 tests in 17.671s

FAILED (errors=4)

**Comment by holger-nutonomy** [comment]
Hi. I believe you didn't install the map expansion from https://www.nuscenes.org/download. Give it a try. If it doesn't work here, please post the contents of your maps folder.

**Comment by RevathiTS** [comment]
Hi Holger,
Thanks for the solution provided. The error is resolved. Now the verification of the nuscenes-devkit installation using  the command "python -m unittest" is  giving following results.

(nuscenes) teroot@Nuvo-5000-Perception:~/nuscenes-devkit/python-sdk$ python -m unittest
....................................................................................................................................................................................
----------------------------------------------------------------------
Ran 200 tests in 26.181s

OK

**Comment by holger-nutonomy** [comment]
Great. Have fun!
