### ISSUE TITLE
 Error: nuScenes-lidarseg not installed

### ISSUE THREAD

**Issue by owoshch** [nutonomy/nuscenes-devkit#630]
Hi!

I went through the installation following the tutorial: https://github.com/nutonomy/nuscenes-devkit#nuscenes-lidarseg
Unfortunately, I'm still getting the error in this notebook: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_lidarseg_panoptic_tutorial.ipynb

I made sure that my /datasets/NuScenes/ folder is in the correct format. Could you please guide me which library is missing and how to install it?

# nuscenes-lidarseg
nusc.list_lidarseg_categories(sort_by='count')
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-0aa335bb282b> in <module>
      1 # nuscenes-lidarseg
----> 2 nusc.list_lidarseg_categories(sort_by='count')

~/anaconda3/lib/python3.8/site-packages/nuscenes/nuscenes.py in list_lidarseg_categories(self, sort_by)
    483 
    484     def list_lidarseg_categories(self, sort_by: str = 'count') -> None:
--> 485         self.explorer.list_lidarseg_categories(sort_by=sort_by)
    486 
    487     def list_attributes(self) -> None:

~/anaconda3/lib/python3.8/site-packages/nuscenes/nuscenes.py in list_lidarseg_categories(self, sort_by)
    645                         class index.
    646         """
--> 647         assert hasattr(self.nusc, 'lidarseg'), 'Error: nuScenes-lidarseg not installed!'
    648         assert sort_by in ['count', 'name', 'index'], 'Error: sort_by can only be one of the following: ' \
    649                                                       'count / name / index.'

AssertionError: Error: nuScenes-lidarseg not installed!

**Comment by whyekit-motional** [comment]
Hi @owoshch, pls ensure you have the appropriate version of our devkit installed:
```
$ pip show nuscenes-devkit
Name: nuscenes-devkit
Version: 1.1.5
...
```

**Comment by owoshch** [comment]
> Hi @owoshch, pls ensure you have the appropriate version of our devkit installed:
> 
> ```
> $ pip show nuscenes-devkit
> Name: nuscenes-devkit
> Version: 1.1.5
> ...
> ```

I certainly do. I tried every version from 1.1.5 and lower and get the same result

**Comment by holger-motional** [comment]
@owoshch We are currently rolling out the new panoptic challenge (https://www.nuscenes.org/panoptic) code and haven't updated the pip package yet. We will do so in the next few days. Can you download the source code directly from Github?

**Comment by owoshch** [comment]
> @owoshch We are currently rolling out the new panoptic challenge (https://www.nuscenes.org/panoptic) code and haven't updated the pip package yet. We will do so in the next few days. Can you download the source code directly from Github?

Thank you for the reply! I'm trying to do it and get the following error:

`$ pip install git+https://github.com/nutonomy/nuscenes-devkit.git
Collecting git+https://github.com/nutonomy/nuscenes-devkit.git
  Cloning https://github.com/nutonomy/nuscenes-devkit.git to /tmp/pip-req-build-_rhhx1un
  Running command git clone -q https://github.com/nutonomy/nuscenes-devkit.git /tmp/pip-req-build-_rhhx1un
    ERROR: Command errored out with exit status 1:
     command: /home/fkitashov/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_rhhx1un/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_rhhx1un/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q0bcg0vx
         cwd: /tmp/pip-req-build-_rhhx1un/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/fkitashov/anaconda3/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-_rhhx1un/setup.py'
    ----------------------------------------
WARNING: Discarding git+https://github.com/nutonomy/nuscenes-devkit.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by whyekit-motional** [comment]
@owoshch we just released version `1.1.6` of the devkit: https://pypi.org/project/nuscenes-devkit/1.1.6/

Do give it a shot and see if it works for you

**Comment by owoshch** [comment]
> @owoshch we just released version `1.1.6` of the devkit: https://pypi.org/project/nuscenes-devkit/1.1.6/
> 
> Do give it a shot and see if it works for you

It works, thank you!

**Comment by owoshch** [comment]
Hi @whyekit-motional!
Am I right that NuScenes Panopric Challenge data has not been revealed yet and will be revealed in the upcoming 2 months?

**Comment by whyekit-motional** [comment]
Hi @owoshch, you should be able to download the nuScenes-panoptic dataset from https://www.nuscenes.org/download

Do let @lubing-motional or myself know if you do not see a download link on your end!

**Comment by owoshch** [comment]
@whyekit-motional Thank you! I have successfully downloaded the dataset. Thank you for your work!

**Comment by whyekit-motional** [comment]
Credits to @lubing-motional for the nice nuScenes-panoptic dataset :smile:
