### ISSUE TITLE
AttributeError: 'LineString' object has no attribute 'exterior' 

### ISSUE THREAD

**Issue by lxy-04** [nutonomy/nuscenes-devkit#762]
When I write the following function according to the official example to project the 3D detection result (CenterPoint) to the pixel plane
```
def project_3d_to_2d(nusc, det, yaw, sample_data, cam):
    # 得到对应相机的data
    box = Box(det["translation"],
              det["size"],
              yaw,
              score=det["detection_score"],
              name=det["detection_name"])
    sd_rec = nusc.get('sample_data', sample_data[cam])
    cs_rec = nusc.get('calibrated_sensor', sd_rec['calibrated_sensor_token'])
    pose_rec = nusc.get('ego_pose', sd_rec['ego_pose_token'])
    camera_intrinsic = np.array(cs_rec['camera_intrinsic'])
    # 从世界坐标系->车身坐标系
    box.translate(-np.array(pose_rec['translation']))
    box.rotate(Quaternion(pose_rec['rotation']).inverse)

    # 从车身坐标系->相机坐标系
    box.translate(-np.array(cs_rec['translation']))
    box.rotate(Quaternion(cs_rec['rotation']).inverse)

    # 过滤掉相机光心之后的点(即z < 0)
    corners_3d = box.corners()
    in_front = np.argwhere(corners_3d[2, :] > 0).flatten()
    corners_3d = corners_3d[:, in_front]

    # 将三维点投影到image plane
    corner_coords = view_points(corners_3d, camera_intrinsic, True).T[:, :2].tolist()

    # 过滤掉超过(1600, 900)范围的像素点
    final_coords = export_2d.post_process_coords(corner_coords)

    return final_coords
```
on the validation set, the following error will be reported for the sample whose sample_token is "50c7c32fa4e446119d53d1deb289aa7f"
```
Traceback (most recent call last):
  File "detections_3d.py", line 525, in <module>
    test(nusc, full_results_json)
  File "detections_3d.py", line 470, in test
    sample_token='50c7c32fa4e446119d53d1deb289aa7f')
  File "detections_3d.py", line 219, in token_to_data
    bbox2d = project_3d_to_2d(nusc, det, tmp_yaw, sample_data, cam_name)
  File "detections_3d.py", line 507, in project_3d_to_2d
    final_coords = export_2d.post_process_coords(corner_coords)
  File "/home/lixiaoyu/anaconda3/envs/mm/lib/python3.6/site-packages/nuscenes/scripts/export_2d_annotations_as_json.py", line 42, in post_process_coords
    intersection_coords = np.array([coord for coord in img_intersection.exterior.coords])
AttributeError: 'LineString' object has no attribute 'exterior'
```
this error is not reported in other samples of the validation set, I think that export_2d_annotations_as_json.py may need additional checks for such cases? I'm not sure why this kind of error is reported, hope to get your answer, it's very helpful!!!

**Comment by whyekit-motional** [comment]
@lxy-04 as you did not provide the inputs you used for `nusc`, `det`, `yaw`, `sample_data` and `cam` in your custom method `project_3d_to_2d`, I can't really debug your method much

However, I've tried using the ground truth to test `post_process_coords` (since that's where your code is failing) on 'sample_token = 50c7c32fa4e446119d53d1deb289aa7f`, and I can't seem to reproduce your error

Here's my code snippet for your reference:
```
from collections import OrderedDict
from typing import List

import numpy as np
from pyquaternion.quaternion import Quaternion

from nuscenes.nuscenes import NuScenes
from nuscenes.scripts.export_2d_annotations_as_json import post_process_coords, generate_record
from nuscenes.utils.geometry_utils import view_points


nusc = NuScenes(version='v1.0-trainval', dataroot='/data/sets/nuscenes', verbose=False)


def get_2d_boxes(sample_data_token: str, visibilities: List[str]) -> List[OrderedDict]:
    """
    Get the 2D annotation records for a given `sample_data_token`.
    :param sample_data_token: Sample data token belonging to a camera keyframe.
    :param visibilities: Visibility filter.
    :return: List of 2D annotation record that belongs to the input `sample_data_token`
    """

    # Get the sample data and the sample corresponding to that sample data.
    sd_rec = nusc.get('sample_data', sample_data_token)

    assert sd_rec['sensor_modality'] == 'camera', 'Error: get_2d_boxes only works for camera sample_data!'
    if not sd_rec['is_key_frame']:
        raise ValueError('The 2D re-projections are available only for keyframes.')

    s_rec = nusc.get('sample', sd_rec['sample_token'])

    # Get the calibrated sensor and ego pose record to get the transformation matrices.
    cs_rec = nusc.get('calibrated_sensor', sd_rec['calibrated_sensor_token'])
    pose_rec = nusc.get('ego_pose', sd_rec['ego_pose_token'])
    camera_intrinsic = np.array(cs_rec['camera_intrinsic'])

    # Get all the annotation with the specified visibilties.
    ann_recs = [nusc.get('sample_annotation', token) for token in s_rec['anns']]
    ann_recs = [ann_rec for ann_rec in ann_recs if (ann_rec['visibility_token'] in visibilities)]

    repro_recs = []

    for ann_rec in ann_recs:
        # Augment sample_annotation with token information.
        ann_rec['sample_annotation_token'] = ann_rec['token']
        ann_rec['sample_data_token'] = sample_data_token

        # Get the box in global coordinates.
        box = nusc.get_box(ann_rec['token'])

        # Move them to the ego-pose frame.
        box.translate(-np.array(pose_rec['translation']))
        box.rotate(Quaternion(pose_rec['rotation']).inverse)

        # Move them to the calibrated sensor frame.
        box.translate(-np.array(cs_rec['translation']))
        box.rotate(Quaternion(cs_rec['rotation']).inverse)

        # Filter out the corners that are not in front of the calibrated sensor.
        corners_3d = box.corners()
        in_front = np.argwhere(corners_3d[2, :] > 0).flatten()
        corners_3d = corners_3d[:, in_front]

        # Project 3d box to 2d.
        corner_coords = view_points(corners_3d, camera_intrinsic, True).T[:, :2].tolist()

        # Keep only corners that fall within the image.
        final_coords = post_process_coords(corner_coords)

        # Skip if the convex hull of the re-projected corners does not intersect the image canvas.
        if final_coords is None:
            continue
        else:
            min_x, min_y, max_x, max_y = final_coords

        # Generate dictionary record to be included in the .json file.
        repro_rec = generate_record(ann_rec, min_x, min_y, max_x, max_y, sample_data_token, sd_rec['filename'])
        repro_recs.append(repro_rec)

    return repro_recs


for sensor, sd_token in nusc.get('sample', '50c7c32fa4e446119d53d1deb289aa7f')['data'].items():
    if 'CAM_' in sensor:
        boxes_2d = get_2d_boxes(sd_token, ['', '1', '2', '3', '4'])
        print(f'There are {len(boxes_2d)} boxes in {sensor}')
```

And here's the output of my above code snippet:
```
There are 3 boxes in CAM_FRONT
There are 13 boxes in CAM_FRONT_RIGHT
There are 10 boxes in CAM_BACK_RIGHT
There are 3 boxes in CAM_BACK
There are 1 boxes in CAM_BACK_LEFT
There are 0 boxes in CAM_FRONT_LEFT
```

**Comment by lxy-04** [comment]
I am sorry for not being able to provide more information, there are the centerpoint detection results on 'sample_token = 50c7c32fa4e446119d53d1deb289aa7f` in val set(which in the 'v1.0-trainval')
```
{'sample_token': '50c7c32fa4e446119d53d1deb289aa7f', 'translation': [1302.4542547955987, 894.6844990431649, 0.9593934108369282], 'size': [1.737599492073059, 3.794389247894287, 1.5024027824401855], 'rotation': [-0.9612202077060836, -0.03152498695376447, -0.02362622193017649, 0.27295363916303644], 'velocity': [1.1667576252885999e-09, -7.146640819001918e-09], 'detection_name': 'car', 'detection_score': 0.15190120041370392, 'attribute_name': 'vehicle.parked'}
```
there are the parameters of the custom method `project_3d_to_2d.py`:
```
det = {'sample_token': '50c7c32fa4e446119d53d1deb289aa7f', 'translation': [1302.4542547955987, 894.6844990431649, 0.9593934108369282], 'size': [1.737599492073059, 3.794389247894287, 1.5024027824401855], 'rotation': [-0.9612202077060836, -0.03152498695376447, -0.02362622193017649, 0.27295363916303644], 'velocity': [1.1667576252885999e-09, -7.146640819001918e-09], 'detection_name': 'car', 'detection_score': 0.15190120041370392, 'attribute_name': 'vehicle.parked'}

yaw = -0.961 -0.032i -0.024j +0.273k

sample_data = {'RADAR_FRONT': '237d9fb9a54244b6bf1007c68660bc04', 'RADAR_FRONT_LEFT': 'a1aa8a2040294a3a9b1b3f7e7e240a7b', 'RADAR_FRONT_RIGHT': '3151839c72b2431a9883eae38799b710', 'RADAR_BACK_LEFT': '15883e9101c9430fa18711e35a3a746b', 'RADAR_BACK_RIGHT': '6a7abfcfee3a480c905f2aeb84056548', 'LIDAR_TOP': '956ea355594c47d895a8078665a334de', 'CAM_FRONT': '1976d6671c6b450c8a552ffe8d2d5e4e', 'CAM_FRONT_RIGHT': '4d59aa6737e6481d83a23e4b2e69397b', 'CAM_BACK_RIGHT': 'a172a235e21642b7b12d5011ee7011e4', 'CAM_BACK': '4c9d95681451410983b1afa09152b0a8', 'CAM_BACK_LEFT': 'fad8a65e3b724a8ca575f0333a0ee9be', 'CAM_FRONT_LEFT': '8f6556bb7e5b44ebbe79a32df03a7dd4'}

cam = CAM_BACK_RIGHT

nusc = NuScenes(version='v1.0-trainval', dataroot='/home/qinwenyuan/nuscenes/', verbose=True)
```
For the function you provided, I will debug the code, it's will be very helpful！

**Comment by lxy-04** [comment]
after I output the corner_coords in the following code:
```
 # Project 3d box to 2d.
        corner_coords = view_points(corners_3d, camera_intrinsic, True).T[:, :2].tolist()
```
the `corner_coords` is `[[-755.3102293763981, 355.3141608746959], [-739.2813084898571, 1704.552206960759]]` .As you mentioned in your comment above, `corner_coords` is a `line` rather than a `Polygon`. However I think such cases may arise when using this function`post_process_coords.py`, I think it may be useful to skip such non-compliant parameters(`corner_coords`) in this function

**Comment by whyekit-motional** [comment]
It's a good suggestion - I suppose a check can be done on `len(corner_coords)`, and to `continue` if the criteria is not fulfilled

Although, this would mean that users will never be warned about such invalid boxes

**Comment by whyekit-motional** [comment]
Certainly! :+1: We'll take your feedback into account when we work on the improving the devkit

**Comment by lxy-04** [comment]
> Certainly! 👍 We'll take your feedback into account when we work on the improving the devkit

that will be very nice :blush:
