### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by hamid54** [nutonomy/nuscenes-devkit#794]
Hello,

I tried to install _nuscenes-devkit_ by following [the setup guidelines](https://github.com/nutonomy/nuscenes-devkit#nuscenes-setup), however, when I run the _unittest_ it ends with a series of errors:

```
/home/nuscenes-devkit/python-sdk$ python -m unittest

............................................./home/nuscenes-devkit/python-sdk/nuscenes/map_expansion/map_api.py:1823: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  exteriors = [int_coords(poly.exterior.coords) for poly in polygons]
/home/nuscenes-devkit/python-sdk/nuscenes/map_expansion/map_api.py:1824: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  interiors = [int_coords(pi.coords) for poly in polygons for pi in poly.interiors]
...........................ssss....................................EEE.................................../home/nuscenes-devkit/python-sdk/nuscenes/utils/map_mask.py:110: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  img = img.resize((size_x, size_y), resample=Image.NEAREST)
/home/nuscenes-devkit/python-sdk/nuscenes/utils/map_mask.py:64: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  on_mask = np.ones(px.size, dtype=np.bool)
....
======================================================================
ERROR: test_classes (nuscenes.tests.test_lidarseg.TestNuScenesLidarseg)
Check that the class names match the ones in the colormap, and are in the same order.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nuscenes-devkit/python-sdk/nuscenes/tests/test_lidarseg.py", line 31, in test_classes
    for name, idx in self.nusc.lidarseg_name2idx_mapping.items():
AttributeError: 'NuScenes' object has no attribute 'lidarseg_name2idx_mapping'

======================================================================
ERROR: test_num_classes (nuscenes.tests.test_lidarseg.TestNuScenesLidarseg)
Check that the correct number of classes (32 classes) are loaded.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nuscenes-devkit/python-sdk/nuscenes/tests/test_lidarseg.py", line 16, in test_num_classes
    self.assertEqual(len(self.nusc.lidarseg_idx2name_mapping), 32)
AttributeError: 'NuScenes' object has no attribute 'lidarseg_idx2name_mapping'

======================================================================
ERROR: test_num_colors (nuscenes.tests.test_lidarseg.TestNuScenesLidarseg)
Check that the number of colors in the colormap matches the number of classes.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nuscenes-devkit/python-sdk/nuscenes/tests/test_lidarseg.py", line 22, in test_num_colors
    num_classes = len(self.nusc.lidarseg_idx2name_mapping)
AttributeError: 'NuScenes' object has no attribute 'lidarseg_idx2name_mapping'

----------------------------------------------------------------------
Ran 181 tests in 32.328s

FAILED (errors=3, skipped=6)
```

Is there anything that I forget to install? Could it be a wrong version? 

Thank you!
Hamid

**Comment by whyekit-motional** [comment]
@hamid54 if you are not going to be using Panoptic nuScenes, you can ignore `test_lidarseg.py`
