### ISSUE TITLE
  KeyError: '61'

### ISSUE THREAD

**Issue by phil695** [nutonomy/nuscenes-devkit#813]
Hi,
Thank you for the wonderful work!
I have a problem:
    
> Traceback (most recent call last):
    File "nuScenes_data.py", line 317, in
    main(args)
    File "nuScenes_data.py", line 112, in main
    test=args.test)
    File "/home/d/Desktop/code/PlanningAwareEvaluation/pred_metric/environment/nuScenes_data/nuScenes_env.py", line 672, in gen_expert_data
    nusc_map = NuScenesMap(dataroot=self.data_root, map_name=self.helper.get_map_name_from_sample_token(scene.name))
    File "/home/d/anaconda3/envs/gca/lib/python3.6/site-packages/nuscenes/prediction/helper.py", line 381, in get_map_name_from_sample_token
    sample = self.data.get('sample', sample_token)
    File "/home/d/anaconda3/envs/gca/lib/python3.6/site-packages/nuscenes/nuscenes.py", line 207, in get
    return getattr(self, table_name)[self.getind(table_name, token)]
    File "/home/d/anaconda3/envs/gca/lib/python3.6/site-packages/nuscenes/nuscenes.py", line 216, in getind
    return self._token2ind[table_name][token]
    KeyError: '61'
    Generating Data: 0%|

Do you have any recommendations what my issue might be

Thanks!
Phil

**Comment by whyekit-motional** [comment]
@phil695 since there's only your error msg to go by, I can only make a guess at what the issue might be

I suspect the issue lies with `self.helper.get_map_name_from_sample_token(scene.name)`

The method name `get_map_name_from_sample_token` implies that the method consumes a sample token - however, you are giving it a scene name, which is probably why the `KeyError: '61`` is being thrown
