### ISSUE TITLE
Key error issue

### ISSUE THREAD

**Issue by ParkJunYeop** [nutonomy/nuscenes-devkit#825]
from the tracking result format I think I've made the same json file format which is described here:

https://www.nuscenes.org/tracking?externalData=all&mapData=all&modalities=Any

But I don't know why key error message happens when I run evaluate file. From results format, I also uploaded empty prediction list to my json file, does this matter?

I've uploaded some screen shots of my json file could anyone help with my issue?

![screen1](https://user-images.githubusercontent.com/61575966/192453207-72e5b451-4fab-4a94-bf6a-a1affe06c2b5.png)
![screen2](https://user-images.githubusercontent.com/61575966/192453202-4350598a-8929-4fa5-bd5a-070d2a9fe87b.png)
![screen3](https://user-images.githubusercontent.com/61575966/192453197-212ac32d-5805-4449-8976-c233adfc0219.png)
![screen4](https://user-images.githubusercontent.com/61575966/192453187-4278c5c5-3793-409a-8927-fbcd5c5946e4.png)

**Comment by whyekit-motional** [comment]
@ParkJunYeop I would suggest to paste the actual error in your issue as well

**Comment by ParkJunYeop** [comment]
This is the error I get:

Initializing nuScenes tracking evaluation
Traceback (most recent call last):
  File "/home/yeop/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/my_eval.py", line 52, in <module>
    render_classes=render_classes_)
  File "/home/yeop/.local/lib/python3.6/site-packages/nuscenes/eval/tracking/evaluate.py", line 84, in __init__
    verbose=verbose)
  File "/home/yeop/.local/lib/python3.6/site-packages/nuscenes/eval/common/loaders.py", line 39, in load_prediction
    all_results = EvalBoxes.deserialize(data['results'], box_cls)
  File "/home/yeop/.local/lib/python3.6/site-packages/nuscenes/eval/common/data_classes.py", line 133, in deserialize
    eb.add_boxes(sample_token, [box_cls.deserialize(box) for box in boxes])
  File "/home/yeop/.local/lib/python3.6/site-packages/nuscenes/eval/common/data_classes.py", line 133, in <listcomp>
    eb.add_boxes(sample_token, [box_cls.deserialize(box) for box in boxes])
  File "/home/yeop/.local/lib/python3.6/site-packages/nuscenes/eval/tracking/data_classes.py", line 326, in deserialize
    return cls(sample_token=content['sample_token'],
KeyError: 'sample_token'

**Comment by ParkJunYeop** [comment]
The result for printing content is shown as follws:

![image](https://user-images.githubusercontent.com/61575966/192539177-a56a8301-6a87-435c-afaf-82bbee7d3160.png)

I get error when there's no tracking_result but only sample_token shown in third image from previous comment

Could you tell me the wrong thing in my result_format? I think there's something wrong when there's no object tracked in each of sample_token.
