### ISSUE TITLE
IndexError when following the map expansion tutorial

### ISSUE THREAD

**Issue by AngelosSE** [nutonomy/nuscenes-devkit#878]
My code:

```
from nuscenes.map_expansion.map_api import NuScenesMap

DATAROOT = <path-to-data>
nusc_map = NuScenesMap(dataroot=DATAROOT, map_name='singapore-onenorth')
fig, ax = nusc_map.render_layers(nusc_map.non_geometric_layers, figsize=1)

```

Error:
Traceback (most recent call last):
  File "<a_path>/tutorial_map_expansion.py", line 23, in <module>
    fig, ax = nusc_map.render_layers(nusc_map.non_geometric_layers, figsize=1)
  File "<a_path>/python3.10/site-packages/nuscenes/map_expansion/map_api.py", line 257, in render_layers
    return self.explorer.render_layers(layer_names, alpha,
  File "<a_path>/python3.10/site-packages/nuscenes/map_expansion/map_api.py", line 982, in render_layers
    self._render_layer(ax, layer_name, alpha, tokens)
  File "<a_path>/python3.10/site-packages/nuscenes/map_expansion/map_api.py", line 1691, in _render_layer
    self._render_polygon_layer(ax, layer_name, alpha, tokens)
  File "<a_path>/python3.10/site-packages/nuscenes/map_expansion/map_api.py", line 1734, in _render_polygon_layer
    ax.add_patch(descartes.PolygonPatch(polygon, fc=self.color_map[layer_name], alpha=alpha,
  File "<a_path>/python3.10/site-packages/descartes/patch.py", line 87, in PolygonPatch
    return PathPatch(PolygonPath(polygon), **kwargs)
  File "<a_path>/python3.10/site-packages/descartes/patch.py", line 62, in PolygonPath
    vertices = concatenate([
  File "<a_path>/python3.10/site-packages/descartes/patch.py", line 63, in <listcomp>
    concatenate([asarray(t.exterior)[:, :2]] +
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

My folder structure is 
-v1.0-trainval_meta
--Maps
---prediction
---basemap
---expansion
--v1.0-trainval

Platform: OSX

**Comment by whyekit-motional** [comment]
@AngelosSE your error looks similar to the one in https://github.com/nutonomy/nuscenes-devkit/issues/863

You can choose to do one of the following:

- Downgrade `Shapely` to `1.8.5`
  ```
  pip uninstall shapely -y && pip install shapely==1.8.5
  ```
- Upgrade `nuscenes-devkit` to `1.1.10`
  ```
  pip uninstall nuscenes-devkit -y && pip install nuscenes-devkit==1.1.10
  ```
